sudo: true
language: node_js
node_js: "6"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

services:
  - postgresql

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - public
    - tmp

env:
  # Build options
  - RAKE_ENV=test
    DISPLAY=:99.0
    JAVASCRIPT_DRIVER=chrome_headless
    GCLOUD_PROJECT_ID="todo-app-rails"
    GCLOUD_KEYFILE=""

install:
  - bundle install
  - yarn install --pure-lockfile

before_script:
  # Setup database
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1400x900x16
  - sleep 3
  - chromedriver-update
  - google-chrome-stable --headless --no-sandbox --no-gpu
  - bundle exec rake db:setup
  - bundle exec rake db:seed

script:
  - yarn run test
  # @TODO
  # - yarn run lint
